version: "3.8"
services:
  fbf-phv3:
    build: .
    image: rodekruis510/typhoonmodel
    ports:
      - "587:587"
    #container_name: ibf
    env_file:
      - secrets
    volumes:
      - './documentation:/home/fbf'      #- $TYPHOONMODEL_OUTPUT:/home/fbf
    command: run-typhoon-model #command: run-typhoon-model  --typhoonname="RAI" --remote_directory='20211214000000'
     
