version: "3.8"
services:
  fbf-phv3:
    build: .
    image: rodekruis510/typhoonibf:latest
    ports:
      - "587:587"
    env_file:
      - secrets
    volumes:
      #- "C:/data/forecast:/home/ibf"
      - $TYPHOONMODEL_OUTPUT:/home/fbf/forecast
    #command: run-typhoon-model  --typhoonname="RAI" --remote_directory='20211214000000'
    command: run-typhoon-model 
